### ISSUE TITLE
add timeout function to reset session

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#12]
@mushon will explore this function in Kiosk apps

**Comment by mushon** [comment]
this is not a function currently supported by Framer, which otherwise is quite reliable.

**Comment by mushon** [comment]
I tried this function on other Kiosk apps and I'm afraid it's problematic as even the ones that do have it reload the page and by that leave it on the same hash url state.
Moreover, we might be getting interaction via water pouring that the kiosk can't detect, in which case there will be no way for us to know if someone isn't simply pouring water slowly and marveling the drops or just left the work without completing the session.

I think we're better off implementing this in the software. Here's a suggestion:
after let's say 15 seconds of no input, show this screen:
![image](https://cloud.githubusercontent.com/assets/27123/20028725/29c4283a-a342-11e6-9ae5-3d4fe7c76d97.png)
any tap will break the countdown, if the countdown finishes, we go back to state 1.
We will need this in a few places:
- if no additional water was poured and the confirm button wasn't tapped after 15secs
- if the map gets no interaction after 15secs
- if the email entry form gets no interaction after 15secs

**Comment by wonyoungso** [comment]
Done! (since I feel like 15 sec is not enough so changed to 20sec)
