### ISSUE TITLE
delay adding of each drop for increased pleasure

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#18]
right now drops are added in batches, to make the visual experience more compelling we should add each drop individually in a split second delay (I'd recommend starting with 10ms, we can play with it and optimize). That way the rows will fill quickly and the animation will be more compelling. @wonyoungso  what say you?

**Comment by wonyoungso** [comment]
I can't agree with you more, let's implement

**Comment by mushon** [comment]
Awesome, do you want to push something in the code for me to play with? I'm assuming this should be a delayed loop with the final drop count as the top bar for looping. Once it's in, I can play with the delay and the CSS to finalize it.

**Comment by wonyoungso** [comment]
Let me do this thing today evening and I'll let you know!

**Comment by wonyoungso** [comment]
implemented `setAnim` in webpack/pages/PourWater.js. it's 10ms interval. But I think it's quite slow when we assume that an audience pour 220ml water, which converts to over 4000 drops. thoughts?

**Comment by wonyoungso** [comment]
changed adding drops 1 in a frame to 2

**Comment by mushon** [comment]
Did you check my commits from today, I think it works quite nicely. But I agree we could go with two drops per frame for better performance.
