### ISSUE TITLE
add scope classes to ul.drops

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#19]
I might want to start shrinking the drop sizes as the water is poured in. For that I need a dynamic class on the ul.drops element that I can play with like `.scale1` `.scale2` `.scale3` that I can use after we go over X drops. @wonyoungso can you mock something up for me to play with? (we might want to use this on the Congratulation page too)

**Comment by wonyoungso** [comment]
Just revised. You can play with the quantize scale written in:
/webpack/reducers/index.js at line 16 `dropClassScale`

it changes from `scale1` -> to `scale2` ->  to `scale3`
