### ISSUE TITLE
Map is not loaded on state 4

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#20]
not sure why, it is nowhere to find in my dom

**Comment by wonyoungso** [comment]
it works..?

**Comment by mushon** [comment]
This might only be a local problem, but on my installation I can't get the map to load at all, no trace in the DOM and no error in the console. This might be due to something missing in the installation process. Please advise (reopening)

**Comment by mushon** [comment]
See? Nothing here:
![image](https://cloud.githubusercontent.com/assets/27123/19550652/2c8c35a8-96b3-11e6-9faa-686a10a6ff6a.png)
(Just a reminder that I am running on localhost with `rails s webrick`, trying to use `npm start` instead results in errors)

**Comment by wonyoungso** [comment]
`rails s webrick` and `npm start` is the only two command you should use and if the dom is rendered, it means that it's running properly. strange.. is there any errors or warnings on console? 

Maybe trying to remove /public/webpack could be helpful to debug.
(after you've done the debug, don't forget to recompile the code by `bundle exec rake webpack:compile`)

**Comment by mushon** [comment]
Let's try to fix this somehow, as it's currently baring further development. Moreover, I suggest we load the map on state 1 so it is already ready and fully rendered when we get to state 4. What do you think @wonyoungso ?

**Comment by wonyoungso** [comment]
Since the structure of the application is not allowed to load like that, It's almost impossible to do that. To do this we revise all the structure and I cannot guarantee the stability of the app.

**Comment by wonyoungso** [comment]
Revise a bit -- can you check?

**Comment by mushon** [comment]
Hallelujah!
