### ISSUE TITLE
state transition fixes

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#25]
state 3 (congratulations) should lead automatically to the state 4—map-invest (after 1000ms delay)
state 4 (map-invest) should lead automatically to the state 5—email form (after 1000ms delay)

**Comment by wonyoungso** [comment]
I'm not sure, in state 4, whether or not we should implement this since the tablet doesn't have kinda..mousemove event which can detect subtle movement of a user.

**Comment by mushon** [comment]
maybe we should simply add a delay in both of these states. There is value in reading that final message but nothing prompts (or should require) an extra tap. So a 1000ms delay would probably the best way to go (for both of these transitions). right?

**Comment by wonyoungso** [comment]
ah I see your point now.. I tested them with 1000ms but it's not enough. set it with 2000ms.
