### ISSUE TITLE
map on iPad is larger than it should be

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#36]
iPad might be too slow in assigning the size dynamically. Any idea how to force it to be width: `974px;` & `height: 518px`?

**Comment by wonyoungso** [comment]
if you found the right size, then let me know—i'll change.

**Comment by mushon** [comment]
![image](https://cloud.githubusercontent.com/assets/27123/20045707/0cff5926-a4e7-11e6-90b4-e8dd4bd7a296.png)

**Comment by mushon** [comment]
It's the size I wrote you

**Comment by wonyoungso** [comment]
done!

**Comment by mushon** [comment]
it's very weird. it only happens on the iPad

**Comment by mushon** [comment]
I might have to patch it with a white div or something…

**Comment by wonyoungso** [comment]
is the screenshot the problem? overflowing? then could be the solution about resizing a bit more?

**Comment by mushon** [comment]
yes, the screenshot represents the problem, but the thing is this bug happens only inside the Kiosk app. Even Safari on the iPad presents it correctly.

**Comment by mushon** [comment]
patched in https://github.com/mushon/IWBA/commit/a7d42a0df14e088e737c83d82e7ba59893c08433
