### ISSUE TITLE
Upgrade Dynos in heroku

### ISSUE THREAD

**Issue by wonyoungso** [mushon/IWBA#39]
1. adding credit card info to your heroku account 

2. upgrade dynos into hobbys
<img width="996" alt="screenshot 2016-11-07 23 14 33" src="https://cloud.githubusercontent.com/assets/376269/20086667/0e754f0a-a540-11e6-9c5e-c52cb661c93c.png">

**Comment by mushon** [comment]
running on one station. we're good.
