### ISSUE TITLE
communicate with Sungil about iPad power

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#5]

**Comment by mushon** [comment]
Just to make sure, Sungil is aware we'll be using iPad 3 with iPhone 4 style charger chord:
![image](https://cloud.githubusercontent.com/assets/27123/19559483/c5862f32-96d8-11e6-81c8-1ad685d3674f.png)
If yes, close this issue.

**Comment by wonyoungso** [comment]
I'm also planning to buy an adapter for the iPad. By the way, I'm still kinda worrying about the performance of the iPad because of the map..

**Comment by mushon** [comment]
I can bring one with me to Seoul.
- I tested (and will continue testing) the iPad, so far so good.

**Comment by wonyoungso** [comment]
It should be long enough to..over 2m?

**Comment by mushon** [comment]
Wouldn't it be simpler to get a power extension up to where the iPad and sensor are?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
