### ISSUE TITLE
hotspot interaction

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#7]
SVG marker for empty hotspot
SVG marker for invested hotspot
resize marker by scale of investment

**Comment by mushon** [comment]
We'll be using these 3 icons:

![uploads/ea5002b7-83b8-4ea6-95e9-1da58a4da274/marker-scale.svg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fea5002b7-83b8-4ea6-95e9-1da58a4da274%2Fmarker-scale.svg)

![uploads/515c4577-2f41-4a14-b985-5b725788fada/marker-invested.svg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F515c4577-2f41-4a14-b985-5b725788fada%2Fmarker-invested.svg)

![uploads/e468aefa-20d2-497b-9aed-c37cf7f20b7f/marker.svg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe468aefa-20d2-497b-9aed-c37cf7f20b7f%2Fmarker.svg)

like this:

![uploads/87b363d0-ec50-4328-bb53-c3265c0dce30/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F87b363d0-ec50-4328-bb53-c3265c0dce30%2Fblob)

@wonyoungso please feedback / implement

**Comment by wonyoungso** [comment]
can you add the images onto the mapbox studio? there's guide: https://www.mapbox.com/help/custom-markers/

**Comment by mushon** [comment]
Will do.

**Comment by mushon** [comment]
published as:
`marker-scale.svg`
and
`marker-invested.svg`

**Comment by wonyoungso** [comment]
Is there a reason you don't upload this one? it may be the default icon..

![screenshot 2016-11-05 11 37 01](https://cloud.githubusercontent.com/assets/376269/20031343/541bf11c-a34c-11e6-8623-252a0af1e105.png)

**Comment by mushon** [comment]
missed it.
`marker.svg`

**Comment by wonyoungso** [comment]
Done!
