### ISSUE TITLE
implement map toggle

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#9]
use mapbox style transition.
@mushon will enter the color hex numbers and will reassign to @wonyoungso

**Comment by mushon** [comment]
Rather than style transition I think we can use layer transparency. We'll have layers for both color scales and then fade them in/out via JS. I will post the layer names tomorrow so @wonyoungso can experiment with it.

**Comment by mushon** [comment]
ok, I finally managed to get zooms 0-3 working.
Now we can add a checkbox (which I will style as a toggle) for switching layer visibility.
The 5 drought layers start with `drought-*` and are visible by default, the 5 profit layers start with `profit-*` and are off by default. The toggle should switch the visibility of these 5:

Default drought mode:
![image](https://cloud.githubusercontent.com/assets/27123/19857578/db5d708e-9f86-11e6-877d-ada524a13b44.png)

Profit mode:
![image](https://cloud.githubusercontent.com/assets/27123/19857605/f19e4774-9f86-11e6-963a-fc34e409e8ea.png)

**Comment by wonyoungso** [comment]
Done except adding toggle button. implemented in webpack/components/MapToggleBtn.js

**Comment by mushon** [comment]
Switch the toggle behavior from layer visibility to layer opacity (ideally animated) for better responsiveness of the map toggle

**Comment by wonyoungso** [comment]
It's almost impossible...
